# -*- coding: utf-8 -*-
"""creating API using Gemini API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbfiWDGmMsiDovBNgedRqo-IeC6YD7II
"""

## use googke AI studio
## create api key

## google Gemini API for which library is needed for generative AI
!pip install -q -U google generativeai

import google.generativeai as genai
genai.configure(api_key= 'AIzaSyCsjOcqVHRjkk2SIFo8OaXpBvy6jt8yTdM')

models = genai.list_models()
for i in models:
  print(i.name)

model =genai.GenerativeModel('gemini-2.5-pro')
response = model.generate_content('Write a short poem about rains')
print(response.text)

## control the models by parameter
# temparature -  control the randomness or creativity of the model response by influencing (tolen/words) selection probabiity
#-- low temp(0.1,0.3) -- results in conservative, predictable response fact focused.
#-- this is the most probable and repetive and concize response
#  -- high temp( .7  to 1 ) increases the random ness , less probable tokens et selected, this will produce most diverse creative ,un expected responses.
## these are for creative responses use high temparature
#################################################

# system_prompts -a hidden instruction or set of guidlines provided to the model before the user queries

# purpose -ensures consisitancy
# Max token - no. of token a response of model can have

#Total tokens , top_k - diversity in selection of token
# top p -

print(response)

model2 = genai.GenerativeModel('gemini-2.5-pro',
                               generation_config={
                                   "temperature" :0.9,
                                   "max_output_tokens" :10000
                               })

prompt ="You are a creative poem writter write a poem on bird"
response = model2.generate_content(prompt)
print(response.text)

## Images
from PIL import Image

img = Image.open("/content/sample_data/fruits.png")
img.resize((224,224))

res = model.generate_content(["Write a short details about the image", img])
print(res.text)

!pip install gradio

import gradio as gr ## used for UI

def analyze_image(image,prompt):
  if not image or not prompt:
    return "Please Upload the image and enter a prompt"

  response =model2.generate_content([prompt,image])
  return response.text

app = gr.Interface(
    fn= analyze_image,
    inputs=[
           gr.Image(type='pil',label='upload image'),
           gr.Textbox(lines=2,placeholder="Enter a prompt(e.g. Describe this image)")
          ],
    outputs ="text",
    title="gemini vision assistance",
    description= "Upload image and ask anything about it"
)

app.launch()
